name: music_streaming_mobile
description: Radiosesel a custom radio and music streaming mobile app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # admob_flutter: ^3.0.0
  cupertino_icons: ^1.0.2
  firebase_crashlytics: ^2.8.2
  xml: ^6.2.2
  xml2json: ^5.3.6
  flutter_zoom_drawer: ^3.0.4+1
  google_mobile_ads: 3.0.0
  share_plus: ^7.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  firebase_storage: ^10.2.17
  firebase_core_platform_interface: 4.5.1
  cloud_firestore: ^3.1.17
  shared_preferences: ^2.0.15
  supercharged: ^2.1.1
  simple_animations: ^4.1.0
  http: ^0.13.4
  flutter_easyloading: ^3.0.5
  connectivity: ^3.0.6
  country_picker: ^2.0.15
  intl: 
  easy_localization: 
  another_flushbar: ^1.10.29
  flutter_cache_manager: ^3.3.0
  infinite_carousel: ^1.0.2
  get_it: ^7.2.0
  we_slide: ^2.3.0
  get: ^4.6.5
  flutter_radio_player: ^1.1.0
  flutter_html: ^3.0.0-alpha.6
  url_launcher: ^6.1.5
  shimmer: ^3.0.0
  marquee: ^2.2.3
  # flutter_inapp_purchase: ^5.3.1
  
dev_dependencies:

  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  dart_code_metrics: ^4.16.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Bold.ttf
        - asset: assets/fonts/lato/Lato-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
        - asset: assets/fonts/raleway/Raleway-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
